### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by craSH**
Fix README markdown headers

### CODE REVIEW

**Comment by zenspider** [comment]
The headers weren't broken because they were rdoc, not markdown.

**Comment by craSH** [comment]
Oops, sorry about that! Would you mind if it were renamed to .rdoc ? That'd make Github render it, is all. This particular pull request can be nuked though.

**Comment by zenspider** [comment]
> On May 18, 2015, at 16:07, Ian Gallagher <notifications@github.com> wrote:
> 
> Oops, sorry about that! Would you mind if it were renamed to .rdoc ? That'd make Github render it, is all. This particular pull request can be nuked though.

No, I'm not against the rename. Need to change the Rakefile as well so that my system still works for gem builds / deploys etc. Just roll back, make the change, and then `git push -f` to your repro to update the PR.

Thanks!

**Comment by craSH** [comment]
Done, looks like it went cleanly. Thanks!

**Comment by zenspider** [comment]
Done. Thanks

**Pull request closed without merging**
